./ASTARStowage.sh ./ASTAR-tests mapa1 contenedores1 heuristic1
./ASTARStowage.sh ./ASTAR-tests mapa1 contenedores1 heuristic2
./ASTARStowage.sh ./ASTAR-tests mapa1 contenedores2 heuristic1
./ASTARStowage.sh ./ASTAR-tests mapa1 contenedores2 heuristic2
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores3 heuristic1
./ASTARStowage.sh ./ASTAR-tests mapa3 contenedores3 heuristic2
./ASTARStowage.sh ./ASTAR-tests mapa4 contenedores4 heuristic1
./ASTARStowage.sh ./ASTAR-tests mapa4 contenedores4 heuristic2
./ASTARStowage.sh ./ASTAR-tests mapa5 contenedores5 heuristic1
./ASTARStowage.sh ./ASTAR-tests mapa5 contenedores5 heuristic2
./ASTARStowage.sh ./ASTAR-tests mapa6 contenedores6 heuristic1
./ASTARStowage.sh ./ASTAR-tests mapa6 contenedores6 heuristic2