python ./CSPStowage.py ./CSP-tests mapa1 contenedores1
python ./CSPStowage.py ./CSP-tests mapa2 contenedores2
python ./CSPStowage.py ./CSP-tests mapa3 contenedores3
python ./CSPStowage.py ./CSP-tests mapa4 contenedores4
python ./CSPStowage.py ./CSP-tests mapa5 contenedores5
python ./CSPStowage.py ./CSP-tests mapa6 contenedores6
python ./CSPStowage.py ./CSP-tests mapa7 contenedores6
python ./CSPStowage.py ./CSP-tests mapa2 contenedores4
python ./CSPStowage.py ./CSP-tests mapa8 contenedores6